<?php
/**
* Implementation of hook_node_info().
*/
function carikegiatan_node_info() {
return array(
'carikegiatan' => array(
'name' => t('Cari Kegiatan'),
'module' => 'carikegiatan',
'description' => t('How to create a Cari Kegiatan.'),
)
);
}

/**
* Access Permission of this module by hook_perm();
*/
function carikegiatan_perm() {
return array('access carikegiatan content');
}

/**
* Implementation of hook_block().
*/
function carikegiatan_block($op='list', $delta=0) {
// listing of blocks, such as on the admin/block page
if ($op == “list”) {
$block[0][“info”] = t('Cari Kegiatan');
return $block;
}
else if($op == 'view')
{
$block_content="Halo";
$block['subject'] = 'Cari Kegiatan';
$block['content'] = $block_content;
return $block;
}
}