<?php
 
/**
 * For more informaiton about the different API controls available see:
 * http://api.drupal.org/api/drupal/developer--topics--forms_api_reference.html/6
 */
 
function kasgaji_menu() {
    $items['kasgaji'] = array(
        'title' => 'Anggaran Kas Belanja Langsung',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('kasgaji_form'),
        'access callback' => TRUE,
    );
    return $items;
}
 
/**
 * This is form containing every form element type available.
 */
function kasgaji_form() {
	drupal_add_css('files/css/kegiatancam.css');
	//drupal_add_js('files/js/kegiatancam.js');
	
	$kodekeg=arg(1);
	$otomatis = arg(2);

	$title = 'Anggaran Kas ';
	drupal_set_html_head('<style>label{font-weight: bold; display: block; width: 200px; float: left;}</style>');
	
	if (isset($kodekeg)) {
        $sql = 'select kodekeg,kegiatan,total,tw1,tw2,tw3,tw4 from {kegiatanskpd} where {kodekeg}=\'%s\'';
        $res = db_query(db_rewrite_sql($sql), array ($kodekeg));
        if ($res) {
            $data = db_fetch_object($res);
			if ($data) {
				$title .= $data->kegiatan;
				$anggaran = $data->total;
				$tw1 = $data->tw1;
				$tw2 = $data->tw2;
				$tw3 = $data->tw3;
				$tw4 = $data->tw4;
				
			}
		}
		
	} 

	drupal_set_title($title);
	
	$form['formdata']['kodekeg']= array(
		'#type'         => 'hidden', 
		'#default_value'=> $kodekeg, 
	); 
	$form['formdata']['otomatis']= array(
		'#type'         => 'hidden', 
		'#default_value'=> $otomatis, 
	); 
	

	$form['formdata']['anggaran']= array(
		'#type'         => 'textfield', 
		'#title'        => 'Anggaran',
		'#attributes'	=> array('style' => 'text-align: right'),
		'#size'         => 30, 
		'#default_value'=> apbd_fn($anggaran), 
	); 
	$form['formdata']['e_anggaran']= array(
		'#type'         => 'hidden', 
		'#default_value'=> $anggaran, 
	); 


	$weight = 0;
	$bulan = 0;
	$rows= array();

	if (isset($otomatis)) {
		$o_gaji = round(($anggaran/1000) / 14) * 1000;

		for ($bulan = 1; $bulan <= 11; $bulan++) {
			$weight += 1;

			if ($bulan==3)
				$tw = apbd_fn($tw1);
			else if ($bulan==6)
				$tw = apbd_fn($tw2);
			else if ($bulan==9)
				$tw = apbd_fn($tw3);
			else if ($bulan==12)
				$tw = apbd_fn($tw4);
			else
				$tw = '';
		
			if ($bulan == 6 or $bulan == 7) {
				$rows[] = array (
								'id' => $weight,
								'tag' => 'new',
								'bulan' => $bulan,
								'gaji' => $o_gaji * 2,
								'weight' => $weight,
							);

			} else {
				$rows[] = array (
								'id' => $weight,
								'tag' => 'new',
								'bulan' => $bulan,
								'gaji' => $o_gaji,
								'weight' => $weight,
							);
			}		
		}
		$bulan = 12;
		$weight += 1;
		$rows[] = array (
						'id' => $weight,
						'tag' => 'new',
						'bulan' => $bulan,
						'gaji' => $anggaran - (13 * $o_gaji),
						'tw' => $tw,
						'weight' => $weight,
					);
		$tw = apbd_fn($tw4);
					
	} else {
		$where = sprintf(" where kodekeg='%s'", db_escape_string($kodekeg));
		$sql = 'select kodekeg, bulan, gaji from {anggkasbelanja} ' . $where  . ' order by bulan';
		//($sql);
		$pres = db_query($sql);
		while ($data = db_fetch_object($pres)) {
			$bulan++;
			$weight++;
			
			if ($bulan==3)
				$tw = apbd_fn($tw1);
			else if ($bulan==6)
				$tw = apbd_fn($tw2);
			else if ($bulan==9)
				$tw = apbd_fn($tw3);
			else if ($bulan==12)
				$tw = apbd_fn($tw4);
			else
				$tw = '';		
			
			$rows[] = array (
							'id' => $weight,
							'tag' => 'old',
							'bulan' => $bulan,
							'gaji' => $data->gaji,
							'tw' => $tw,
							'weight' => $weight,
						);
			
		}

		if ($bulan==0) {
			for ($bulan = 1; $bulan <= 12; $bulan++) {
				$weight += 1;

			if ($bulan==3)
				$tw = apbd_fn($tw1);
			else if ($bulan==6)
				$tw = apbd_fn($tw2);
			else if ($bulan==9)
				$tw = apbd_fn($tw3);
			else if ($bulan==12)
				$tw = apbd_fn($tw4);
			else
				$tw = '';
		
				$rows[] = array (
								'id' => $weight,
								'tag' => 'new',
								'bulan' => $bulan,
								'gaji' => 0,
								'tw' => $tw,
								'weight' => $weight,
							);
				
			}
		}
	}
	
    // Tabledrag element
    foreach ($rows as $row) {

        $form['tabledragrows'][$row['id']]['tag_' . $row['id']] = array(
            '#type' => 'hidden',
            '#default_value' => $row['tag'],
            '#size' => 10,
        );

		$form['tabledragrows'][$row['id']]['bulan_' . $row['id']] = array(
			//#type' => 'textfield',
			'#type' => 'markup',
			'#value' => $row['bulan'],
			'#size' => 5,
		);

        $form['tabledragrows'][$row['id']]['gaji_' . $row['id']] = array(
            '#type' => 'textfield',
            '#default_value' => $row['gaji'],
			'#attributes'	=> array('style' => 'text-align: right'),
            '#size' => 20,
        );
        $form['tabledragrows'][$row['id']]['tw_' . $row['id']] = array(
            '#type' => 'markup',
			'#value' => '<p align="right">' . $row['tw'] . '</p>',
            '#size' => 20,
        );
        // the weight form element.
        $form['tabledragrows'][$row['id']]['weight_' . $row['id']] = array(
            '#type' => 'weight',
            '#delta' => 50,
            '#default_value' => $row['weight'],
            '#attributes' => array('class' => 'weight'),
        );
		
    }
 
	
	$form['formdata']['submitoto'] = array(
		'#type' => 'submit',
		'#value' => 'Otomatis',
		//'#weight' => 7,
	);
	$form['formdata']['submit'] = array(
		'#type' => 'submit',
		'#suffix' => "&nbsp;<a href='/apbd/kegiatanskpd' class='btn_blue' style='color: white'>Tutup</a>",
		'#value' => 'Simpan',
		//'#weight' => 7,
	);
	$form['submitoto'] = array(
		'#type' => 'submit',
		'#value' => 'Otomatis',
		//'#weight' => 7,
	);
	$form['submit'] = array(
		'#type' => 'submit',
		'#suffix' => "&nbsp;<a href='/apbd/kegiatanskpd' class='btn_blue' style='color: white'>Tutup</a>",
		'#value' => 'Simpan',
		//'#weight' => 7,
	);

    return $form;
}

/**
 * Implements hook_validate() for the kasgaji_form() form.
 */
function kasgaji_form_validate($form, &$form_state) {
	$e_anggaran = $form_state['values']['e_anggaran'];

	$gaji = 0;
	$t_gaji = 0;
	
	for ($x = 1; $x <= 12; $x++) {
		
		$gaji = $form_state['values']['gaji_' . $x];
		$t_gaji += $gaji;
		
		if ($x<=3) 
			$tw1 += $gaji;
		else if ($x<=6) 
			$tw2 += $gaji;
		else if ($x<=9) 	
			$tw3 += $gaji;
		else
			$tw4 += $gaji;
			
	}	
	
	//Cek 1000
	$seribu = 1000;
	if (($tw1 % $seribu)>0) form_set_error('', 'Jumlah isian Tri Wulan #1 (' . apbd_fn($tw1) . '), tidak bulat per seribu');
	if (($tw2 % $seribu)>0) form_set_error('', 'Jumlah isian Tri Wulan #2 (' . apbd_fn($tw2) . '), tidak bulat per seribu');
	if (($tw3 % $seribu)>0) form_set_error('', 'Jumlah isian Tri Wulan #3 (' . apbd_fn($tw3) . '), tidak bulat per seribu');
	if (($tw4 % $seribu)>0) form_set_error('', 'Jumlah isian Tri Wulan #4 (' . apbd_fn($tw4) . '), tidak bulat per seribu');
	
	//Cek gaji
	if ($t_gaji > $e_anggaran) form_set_error('', 'Jumlah isian anggaran kas (' . apbd_fn($t_gaji) . ') lebih besar daripada anggaran belanja gaji (' . apbd_fn($e_anggaran) . ')');
} 
/**
 * Implements hook_submit() for the kasgaji_form() form.
 */
function kasgaji_form_submit($form, &$form_state) {

	$kodekeg = $form_state['values']['kodekeg'];
    if($form_state['clicked_button']['#value'] == $form_state['values']['submitoto']) {
		$form_state['redirect'] = 'kasgaji/' . $kodekeg . '/oto';
	
	} else {

		$otomatis = $form_state['values']['otomatis'];
		if ($otomatis=='oto') {
			$sql = sprintf("delete from {anggkasbelanja} where kodekeg='%s'", $kodekeg);
			$res = db_query($sql);
		}
	
		$tw1 =0;
		$tw2 =0;
		$tw3 =0;
		$tw4 =0;

		for ($x = 1; $x <= 12; $x++) {
			
			$tag = $form_state['values']['tag_' . $x];
			$gaji = $form_state['values']['gaji_' . $x];

			if ($x<=3) 
				$tw1 += $gaji;
			else if ($x<=6) 
				$tw2 += $gaji;
			else if ($x<=9) 	
				$tw3 += $gaji;
			else
				$tw4 += $gaji;
				
			//Simpan detilnya
			if ($tag == 'new') {

				$sql = "insert into {anggkasbelanja} (kodekeg,bulan,gaji) 
					   values('%s', '%s', '%s')";
				$res = db_query(db_rewrite_sql($sql), array($kodekeg, $x, $gaji));

			} 	else {
				$sql = sprintf("update {anggkasbelanja} set gaji='%s' where kodekeg='%s' and bulan='%s'", $gaji, $kodekeg, $x);
				$res = db_query($sql);
				
			}	
		}	

		//$sql = sprintf("update {kegiatanskpd} set tw1='%s', tw2='%s', tw3='%s', tw4='%s' where kodekeg='%s'", 		$tw1, $tw2, $tw3, $tw4, $kodekeg);
		//$res = db_query($sql);

		if ($res)
			drupal_set_message('Penyimpanan data berhasil dilakukan');
		else
			drupal_set_message('Penyimpanan data tidak berhasil dilakukan');
		
		//drupal_set_message($sql);
	}
}
 
/**
 * Implementation of hook_theme().
 */
function kasgaji_theme() {
    return array(
        'kasgaji_form' => array(
            'arguments' => array(
                'form' => NULL
            ),
        ),
    );
}
 
/**
 * Theme for form_element_form. Used to create the tabledrag element and then
 * render the rest of the form.
 */
function theme_kasgaji_form($form) {
    $table_rows = array();
 
    if (is_array($form['tabledragrows'])) {
        //loop through each "row" in the table array
        foreach ($form['tabledragrows'] as $id => $row) {
            //we are only interested in numeric keys
            if (intval($id)) {
                $this_row = array();
				
				//$this_row[] = drupal_render($form['tabledragrows'][$id]['iddetil_' . $id]);
				$this_row[] = drupal_render($form['tabledragrows'][$id]['space_' . $id]);
                $this_row[] = drupal_render($form['tabledragrows'][$id]['bulan_' . $id]);
                $this_row[] = drupal_render($form['tabledragrows'][$id]['gaji_' . $id]);
                $this_row[] = drupal_render($form['tabledragrows'][$id]['tw_' . $id]);
				
                //Add the weight field to the row
                $this_row[] = drupal_render($form['tabledragrows'][$id]['weight_' . $id]);
 
                //Add the row to the array of rows
                $table_rows[] = array('data' => $this_row);
            }
        }
    }
 
    //Make sure the header count matches the column count
    //$header = array(
     //   "Person",
    //    "Email",
    //    "Weight"
    //);
	$header = array (
				array('data' => '',  'width'=> '0px'),
				 array('data' => 'Bulan',  'width'=> '10px'),
				 array('data' => 'Anggaran Kas',  'width' => '10px'),
				 array('data' => 'Triwulan',  'width' => '10px'), 
				 array('data' => 'Weight'),
				); 
 
    $form['tabledragrows'] = array(
        '#value' => theme('table', $header, $table_rows, array('id' => 'id'))
    );
 
    $output = drupal_render($form);
 
    // Call add_tabledrag to add and setup the JavaScript
    // The key thing here is the first param - the table ID
    // and the 4th param, the class of the form item which holds the weight
    drupal_add_tabledrag('id', 'order', 'sibling', 'weight');
 
    return $output;
}