<?php
 
/**
 * For more informaiton about the different API controls available see:
 * http://api.drupal.org/api/drupal/developer--topics--forms_api_reference.html/6
 */
 
function apbdpendapatanperubahan_menu() {
    $items['apbdpendapatanperubahan'] = array(
        'title' => 'Rekening Pendapatan Revisi',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('apbdpendapatanperubahan_form'),
        'access callback' => TRUE,
    );
    return $items;
}
 
/**
 * This is form containing every form element type available.
 */
function apbdpendapatanperubahan_form() {
	
	drupal_add_css('files/css/kegiatancam.css');
	drupal_add_js('files/js/kegiatanpad.js');
    $form['formdata'] = array (
        '#type' => 'fieldset',
        '#title'=> 'Rekening Pendapatan',
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,        
    );
	
	$kodeuk = arg(1);
	$kodero = arg(2);
	//drupal_set_message($kodeuk);
	
	if (!isSuperuser() and  !isVerifikator())
		$kodeuk = apbd_getuseruk();
		
	//drupal_set_message($kodeuk);
	

	$title = 'Rekening Pendapatan';

	
	$allowedit = (batastgl() || (isSuperuser()));	

	if ($allowedit==false) {
		//dispensasippas
		//$sqluk = sprintf(' and k.kodeuk=\'%s\' ', apbd_getuseruk());	
        $sql = sprintf('select dispensasippas from {unitkerja} where kodeuk=\'%s\'', apbd_getuseruk());
		$res = db_query($sql);
		if ($res) {
			$data = db_fetch_object($res);
			if ($data) {  		
				$allowedit = $data->dispensasippas;
			}
		}
	}
	
	//$title =l($title, 'apbd/pendapatan/' . $kodeuk, array('html'=>true));
	drupal_set_title($title);
	drupal_set_html_head('<style>label{font-weight: bold; display: block; width: 200px; float: left;}</style>');
    $disabled = FALSE;

	$jumlah = 0;
	$jumlahsebelum = 0;
	$jumlahsesudah = 0;
	//$uraian = 'Isikan rekening dengan mengklik tombol Pilih disamping';

	//FILTER TAHUN-----
	$tahun = variable_get('apbdtahun', 0);
	
    if (isset($kodero))
    {
        if (!user_access('kegiatanskpd edit'))
            drupal_access_denied();
			
        $sql = 'select tahun,kodero,uraian,jumlah,jumlahp,jumlahsesudah,ketrekening from {anggperukperubahan} 
			   where tahun=\'%s\' and kodeuk=\'%s\' and kodero=\'%s\'';
        $res = db_query(db_rewrite_sql($sql), array ($tahun, $kodeuk, $kodero));
        if ($res) {
            $data = db_fetch_object($res);
			if ($data) {
                
				$kodero = $data->kodero;
				$uraian = $data->uraian;
				$jumlah = $data->jumlah;
				$jumlahp = $data->jumlahp;
				$jumlahsesudah = $data->jumlahsesudah;
				$ketrekening = $data->ketrekening;
                $disabled =TRUE;
			} else {
				$kodero = '';
			}
        } else {
			$kodero = '';
		}
    } else {
		if (!user_access('kegiatanskpd tambah'))
			drupal_access_denied();
		$form['formdata']['#title'] = 'Tambah Rekening Pendapatan';
		$kodero = '';
	}

    
	$form['formdata']['tahun']= array( 
		'#type'         => 'hidden', 
		'#title'        => 'tahun',  
		'#default_value'=> $tahun, 
	); 	
	$form['formdata']['nk']= array(
		'#type'         => 'hidden', 
		'#title'        => 'kodero', 
		'#default_value'=> $kodero, 
	); 
	$form['formdata']['e_kodero']= array(
		'#type'         => 'hidden', 
		'#title'        => 'kodero', 
		'#default_value'=> $kodero, 
	); 

	$pquery = "select kodeuk, namasingkat from {unitkerja} where aktif=1 order by namauk" ;
	$pres = db_query($pquery);
	$skpd = array();
	$dinas[''] = '--- pilih dinas teknis---';
	while ($data = db_fetch_object($pres)) {
		$skpd[$data->kodeuk] = $data->namasingkat;
	}
	$skpdtype = 'hidden';
	if (isSuperuser() || isAdministrator())
		$skpdtype='select';

	$form['formdata']['kodeuk']= array(
		'#type'         => $skpdtype, 
		'#title'        => 'SKPD',
		'#options'		=> $skpd,
		//'#description'  => 'kodeuk', 
		//'#maxlength'    => 60, 
		//'#size'         => 20, 
		//'#required'     => !$disabled, 
		//'#disabled'     => $disabled, 
		'#default_value'=> $kodeuk, 
	); 
		
	$form['formdata']['kegiatan']= array(
		'#type'         => 'textfield', 
		'#title'        => 'Rekening', 
		//'#description'  => 'uraian', 
		'#maxlength'    => 255, 
		'#size'         => 70, 
		//'#required'     => !$disabled, 
		//'#disabled'     => $disabled, 
		//'#autocomplete_path' => 'apbd/kegiatanrkpd/utils_auto/uraianpendapatan',
		'#default_value'=> $uraian, 
	); 
	$form['formdata']['keterangan'] = array (
		'#type' => 'markup',
		'#value' => "<span><font size='1'>Isi rekening dengan memilih menggunakan tombol Pilih</font></span>",
	);

	$form['formdata']['ketrekening']= array(
		'#type'         => 'textfield', 
		'#title'        => 'Dasar Hukum', 
		//'#description'  => 'Rekening belanja', 
		'#maxlength'    => 255, 
		'#size'         => 70, 
		//'#required'     => !$disabled, 
		//'#disabled'     => $disabled, 
		'#default_value'=> $ketrekening, 
	); 
	
	$form['formdata']['jumlah']= array(
		'#type'         => 'textfield', 
		'#title'        => 'Jumlah',
		'#attributes'	=> array('style' => 'text-align: right'),
		'#disabled'     => true, 
		'#description'  => 'Jumlah anggaran pendapatan, akan terisi saat detil rekening diisikan', 
		//'#maxlength'    => 60, 		'#size'         => 30, 
		//'#required'     => !$disabled, 
		//'#disabled'     => $disabled, 
		'#default_value'=> $jumlahp, 
	); 
	$form['formdata']['penetapan']= array(
		'#type'         => 'textfield', 
		'#title'        => 'Penetapan',
		'#attributes'	=> array('style' => 'text-align: right'),
		'#description'  => 'Jumlah anggaran pendapatan penetapan', 
		//'#maxlength'    => 60, 
		'#size'         => 30, 
		//'#required'     => !$disabled, 
		//'#disabled'     => $disabled, 
		'#default_value'=> $jumlah, 
	); 
	$form['formdata']['jumlahsesudah']= array(
		'#type'         => 'textfield', 
		'#title'        => 'Tahun Depan',
		'#attributes'	=> array('style' => 'text-align: right'),
		'#description'  => 'Jumlah perkiraan anggaran pendapatan tahun depan, seandainya ada', 
		//'#maxlength'    => 60, 
		'#size'         => 30, 
		//'#required'     => !$disabled, 
		//'#disabled'     => $disabled, 
		'#default_value'=> $jumlahsesudah, 
	);
	
	if (isVerifikator()) {
			global $user;
			$username = $user->name;
			
			$ada = false;
			$fsql = sprintf('select jawaban from {anggperukrevisiverifikasi} where kodero=\'%s\' and username=\'%s\'', arg(2), $username);
			//drupal_set_message($fsql);
			$res = db_query($fsql);
			if ($res) {
				if ($data = db_fetch_object($res)) {
					$ada = true;
					$jawaban = $data->jawaban;
				}
			} 	
			$form['formdata']['username']= array(
				'#type'         		=> 'hidden', 
				'#default_value'		=> $username, 
			); 
			$form['formdata']['ada']= array(
				'#type'         		=> 'hidden', 
				'#default_value'		=> $ada, 
			); 
			//PERUBAHAN 
			$form['formdata']['jawaban']= array(
				'#type'         => 'textfield', 
				'#title'        => 'Catatan Verifikator',
				'#description'  => '<font color="red">Catatan/masukan dari verifikator</font>', 
				//'#maxlength'    => 60, 
				'#size'         => 90, 
				//'#required'     => !$disabled, 
				//'#disabled'     => $disabled, 
				'#default_value'=> $jawaban, 
			); 	
			/*$form['formdata']['submitverify'] = array (
				'#type' => 'submit',				
				'#suffix' => "&nbsp;<a href='/apbd/kegiatanrevisiperubahan/rekening/" . $kodekeg . "' class='btn_green' style='color: white'>Tutup</a>",
				'#value' => 'Simpan Catatan Verifikasi',
				//'#weight' => 6,
			);*/
				
			
		}
	$periodeaktif = variable_get('apbdrevisi', 0);
	
	//DETIL
	$where = sprintf(" where kodeuk='%s' and kodero='%s' and tahun='%s'", db_escape_string($kodeuk), db_escape_string($kodero), db_escape_string($tahun));
    $sql = 'select * 
			from {anggperukdetilperubahan}' . $where  . ' order by nourut asc,iddetil';
    $sql = sprintf($sql, addslashes($nama));
	
	//drupal_set_message($sql);
	$resdetil = db_query($sql);
	$weight = 0;
	$rows= array();
	if ($resdetil) {
		//drupal_set_message('res ok');
		while ($data = db_fetch_object($resdetil)) {
			$weight += 1;
			//drupal_set_message($data->uraian . ' - ' . $weight);
			
			if ($data->pengelompokan) {
				$subdetil = l('Detil', 'apbdpendapatanperubahandetil/' . $kodeuk . '/' . $kodero . '/' . $data->iddetil , array('html' =>TRUE));			
				$rows[] = array (
								'id' => $weight,
								'iddetil' => $data->iddetil,
								'space' => '',
								'pengelompokan' => $data->pengelompokan,
								'e_pengelompokan' => $data->pengelompokan,
								'periode' => $data->periode,
								'uraian' => $data->uraianp,
								'unitjumlah' => '1',
								'unitsatuan' => '',
								'volumjumlah' => '1',
								'volumsatuan' => '',
								'harga' => $data->totalp,
								'e_harga' => $data->totalp,
								'subdetil' => $subdetil,
								'ket' => 'Penetapan : ' . $data->uraian . ' (' . $data->unitjumlah . ' ' . $data->unitsatuan . ' x ' . $data->volumjumlah . ' ' . $data->volumsatuan . ' x ' . apbd_fn($data->harga) . ' = ' . apbd_fn($data->total) . ')',										
								'weight' => $weight,
							);

			} else {
				$subdetil = '';			
				$rows[] = array (
								'id' => $weight,
								'iddetil' => $data->iddetil,
								'space' => '',
								'pengelompokan' => $data->pengelompokan,
								'e_pengelompokan' => $data->pengelompokan,
								'periode' => $data->periode,				
								'uraian' => $data->uraianp,
								'unitjumlah' => $data->unitjumlahp,
								'unitsatuan' => $data->unitsatuanp,
								'volumjumlah' => $data->volumjumlahp,
								'volumsatuan' => $data->volumsatuanp,
								'harga' => $data->hargap,
								'e_harga' => $data->hargap,
								'subdetil' => $subdetil,
								'ket' => 'Penetapan : ' . $data->uraian . ' (' . $data->unitjumlah . ' ' . $data->unitsatuan . ' x ' . $data->volumjumlah . ' ' . $data->volumsatuan . ' x ' . apbd_fn($data->harga) . ' = ' . apbd_fn($data->total) . ')',										
								
								'weight' => $weight,
							);
			}
		}
	}
	
	for ($x = 1; $x <= 5; $x++) {
		$weight += 1;

		$rows[] = array (
						'id' => $weight,
						'iddetil' => 'new',
						'space' => '',
						'pengelompokan' => '',
						'e_pengelompokan' => '',
						'periode' => $periodeaktif,
						'uraian' => '',
						'keterangan' => 'Baru',
						'unitjumlah' => '1',
						'unitsatuan' => '',
						'volumjumlah' => '1',
						'volumsatuan' => '',
						'harga' => '',
						'e_harga' => '',
						'subdetil' => '',
						'ket' => 'Baru',
						'weight' => $weight,
					);
	}
	if(!isVerifikator()){
		foreach ($rows as $row) {
			$form['tabledragrows'][$row['id']]['iddetil_' . $row['id']] = array(
				'#type' => 'hidden',
				'#default_value' => $row['iddetil'],
				'#size' => 10,
			);

			$form['tabledragrows'][$row['id']]['space_' . $row['id']] = array(
				'#type' => 'markup',
				'#default_value' => '',
				'#size' => 10,
			);

			$form['tabledragrows'][$row['id']]['pengelompokan_' . $row['id']] = array(
				'#type' => 'checkbox',
				'#default_value' => $row['pengelompokan'],
				'#size' => 10,
			);

			$form['tabledragrows'][$row['id']]['e_pengelompokan_' . $row['id']] = array(
				'#type' => 'hidden',
				'#default_value' => $row['e_pengelompokan'],
				'#size' => 10,
			);

			$form['tabledragrows'][$row['id']]['periode_' . $row['id']] = array(
				'#type' => 'value',
				'#value' => $row['periode'],
			);
			
			$form['tabledragrows'][$row['id']]['uraian_' . $row['id']] = array(
				'#type' => 'textfield',
				'#default_value' => $row['uraian'],
				'#description'  => $row['ket'],
				'#size' => 45,
			);

			$form['tabledragrows'][$row['id']]['unitjumlah_' . $row['id']] = array(
				'#type' => 'textfield',
				'#default_value' => $row['unitjumlah'],
				'#attributes'	=> array('style' => 'text-align: right'),
				'#size' => 5,
			);
			$form['tabledragrows'][$row['id']]['unitsatuan_' . $row['id']] = array(
				'#type' => 'textfield',
				'#default_value' => $row['unitsatuan'],
				'#size' => 10,
			);

			$form['tabledragrows'][$row['id']]['volumjumlah_' . $row['id']] = array(
				'#type' => 'textfield',
				'#default_value' => $row['volumjumlah'],
				'#attributes'	=> array('style' => 'text-align: right'),
				'#size' => 5,
			);
			$form['tabledragrows'][$row['id']]['volumsatuan_' . $row['id']] = array(
				'#type' => 'textfield',
				'#default_value' => $row['volumsatuan'],
				'#size' => 10,
			);

			$form['tabledragrows'][$row['id']]['harga_' . $row['id']] = array(
				'#type' => 'textfield',
				'#default_value' => $row['harga'],
				'#attributes'	=> array('style' => 'text-align: right'),
				'#size' => 10,
			);

			$form['tabledragrows'][$row['id']]['e_harga_' . $row['id']] = array(
				'#type' => 'hidden',
				'#default_value' => $row['e_harga'],
				'#size' => 10,
			);
			
			//'#value' => "<span>$data->program (Kode: $data->kodepro)</span>",
			$form['tabledragrows'][$row['id']]['subdetil_' . $row['id']] = array(
				'#type' => 'markup',
				//'#default_value' => $row['subdetil'],
				//'#value' => "<span>Hai</span>",
				'#value' => $row['subdetil'],
				'#size' => 5,
			);
			
			// the weight form element.
			$form['tabledragrows'][$row['id']]['weight_' . $row['id']] = array(
				'#type' => 'weight',
				'#delta' => 50,
				'#default_value' => $row['weight'],
				'#attributes' => array('class' => 'weight'),
			);
		}
	}
    // Tabledrag element
    
 
	$form['maxdetil']= array(
		'#type'         => 'hidden', 
		'#title'        => 'kodero', 
		'#default_value'=> $weight, 
	); 
 
	if ($kodero != '') {
		//PREV
		$sql = 'select kodero from {anggperukperubahan} where kodeuk=\'%s\' and kodero<\'%s\' order by kodero desc limit 1';
		$res = db_query(db_rewrite_sql($sql), array ($kodeuk, $kodero));
		if ($res) {
			$data = db_fetch_object($res);
			if ($data) {
				$prevkode=$data->kodero;

				$form['prevkode']= array(
					'#type'         => 'hidden', 
					'#default_value'=> $prevkode, 
					//'#weight' => 1,
				);				
				
				
				 
				if(!isVerifikator()){
					$form['formdata']['submitprev'] = array (
						'#type' => 'submit',
						'#value' => '<<',
						//'#weight' => 2,
					);
					$form['submitprev'] = array (
						'#type' => 'submit',
						'#value' => '<<',
						//'#weight' => 2,
					); 
				}
				
				
			}
		}	
		
		//NEXT
		$sql = 'select kodero from {anggperukperubahan} where kodeuk=\'%s\' and kodero>\'%s\' order by kodero limit 1';
		$res = db_query(db_rewrite_sql($sql), array ($kodeuk, $kodero));
		if ($res) {
			$data = db_fetch_object($res);
			if ($data) {
				$nextkode=$data->kodero;

				$form['nextkode']= array(
					'#type'         => 'hidden', 
					'#default_value'=> $nextkode, 
					//'#weight' => 3,
				);				

				
				if(!isVerifikator()){
				$form['formdata']['submitnext'] = array (
					'#type' => 'submit',
					'#value' => '>>',
					//'#weight' => 4,
				);
				$form['submitnext'] = array (
					'#type' => 'submit',
					'#value' => '>>',
					//'#weight' => 4,
				);
				}
			}
		}		
	}

if(isVerifikator()){ 	
	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => 'Setujui',
		//'weight' => 2,
	);
	$form['submittolak'] = array (
		'#type' => 'submit',
		'#value' => 'Tolak',
		//'weight' => 3,
	);				
	$form['submitreset'] = array (
		'#type' => 'submit',
		'#value' => 'Reset',
		'#suffix' => "&nbsp;<a href='/apbd/pendapatanperubahan' class='btn_green' style='color: white'>Tutup</a>",
		//'weight' => 3,
	);
}	
	if(!isVerifikator()){
		$form['formdata']['submitnew'] = array (
			'#type' => 'submit',
			'#value' => 'Rek. Baru',
			//'#weight' => 5,
		);
		$form['formdata']['submitnewdetil'] = array (
			'#type' => 'submit',
			'#value' => 'Tambah Detil',
			//'#weight' => 6,
		);
		$form['formdata']['submit'] = array(
			'#type' => 'submit',
			'#suffix' => "&nbsp;<a href='/apbd/pendapatanperubahan/" . "' class='btn_blue' style='color: white'>Tutup</a>",
			'#value' => 'Simpan',
			//'#weight' => 7,
		);
		$form['submitnew'] = array (
		'#type' => 'submit',
		'#value' => 'Rek. Baru',
		//'#weight' => 5,
		);

		$form['submitnewdetil'] = array (
			'#type' => 'submit',
			'#value' => 'Tambah Detil',
			//'#weight' => 6,
		);
		
		$form['submit'] = array(
			'#type' => 'submit',
			'#suffix' => "&nbsp;<a href='/apbd/pendapatanperubahan/" . "' class='btn_blue' style='color: white'>Tutup</a>",
			'#value' => 'Simpan',
			//'#weight' => 7,
		);
	}
 	
 
    return $form;
}

/**
 * Implements hook_validate() for the apbdpendapatanperubahan_form() form.
 */
function apbdpendapatanperubahan_form_validate($form, &$form_state) {
	$uraianrek = $form_state['values']['kegiatan'];
	$kodero = $form_state['values']['nk'];

	$kodeuk = $form_state['values']['kodeuk'];
	$e_kodero = $form_state['values']['e_kodero'];
	
	$maxdetil = $form_state['values']['maxdetil'];

	if ($kodero=='') 
		form_set_error('', 'Rekening belum diisi');
	
	
	if ($e_kodero != $kodero) {		//Rekening baru
		$sql = 'select kodero from {anggperukperubahan} where kodeuk=\'%s\' and kodero=\'%s\'';
		$res = db_query(db_rewrite_sql($sql), array ($kodeuk, $kodero));
		if ($res) {
			$data = db_fetch_object($res);
			if ($data) {		
				form_set_error('', 'Rekening sudah digunakan');
			}
		}
	} 
	
	//CEK PLAFON
	$totalrekening = 0;
	for ($x = 1; $x <= $maxdetil; $x++) 
	{
		//Hitung detilnya dulu
		$uraian = $form_state['values']['uraian_' . $x];
		$e_pengelompokan = $form_state['values']['e_pengelompokan_' . $x];
		if ($uraian != '') {
			if ($e_pengelompokan) {
				$total = $form_state['values']['e_harga_' . $x];
				
			} else {
				$unitjumlah = $form_state['values']['unitjumlah_' . $x];
				$volumjumlah = $form_state['values']['volumjumlah_' . $x];
				$harga = $form_state['values']['harga_' . $x];

				$total = $unitjumlah * $volumjumlah * $harga;
			}
			$totalrekening += $total;
			
		} 

	}

	//CEK PER 1000
	$seribu = 1000;
	//if ($totalrekening==0)
	//	form_set_error('', 'Isian rekening belum dimasukkan dengan benar, anda harus mengisi detil rekening sehingga jumlah anggaran rekening ada nominal rupiahnya');
	if (($totalrekening % $seribu)>0) form_set_error('', 'Jumlah isian detil rekening ' . apbd_fn($totalrekening) . ', tidak bulat per seribu');

} 
/**
 * Implements hook_submit() for the apbdpendapatanperubahan_form() form.
 */
function apbdpendapatanperubahan_form_submit($form, &$form_state) {
    /*$kodekeg = $form_state['values']['kodekeg'];
	$jawaban = $form_state['values']['jawaban'];
	$ada = $form_state['values']['ada'];
	$username = $form_state['values']['username'];*/
	$kodeuk = $form_state['values']['kodeuk'];
	$tahun = $form_state['values']['tahun'];
	$kodero = $form_state['values']['nk'];
	$jawaban = $form_state['values']['jawaban'];
	$ada = $form_state['values']['ada'];
	$username = $form_state['values']['username'];
	
	$periodeaktif = variable_get('apbdrevisi', 0);
	if(!isVerifikator()){
		if($form_state['clicked_button']['#value'] == $form_state['values']['submitnext']) {
			$nextkode = $form_state['values']['nextkode'];
			$form_state['redirect'] = 'apbdpendapatanperubahan/' .  $kodeuk . '/' . $nextkode ;
			//drupal_set_message('Next');

		} else if($form_state['clicked_button']['#value'] == $form_state['values']['submitprev']) {
			$prevkode = $form_state['values']['prevkode'];
			$form_state['redirect'] = 'apbdpendapatanperubahan/' . $kodeuk . '/' . $prevkode ;
			//drupal_set_message('Next');

		} else {
			
			$e_kodero = $form_state['values']['e_kodero'];			

			
			$uraianrek = $form_state['values']['kegiatan'];
			$ketrekening = $form_state['values']['ketrekening'];
			$kodero = $form_state['values']['nk'];
			$maxdetil = $form_state['values']['maxdetil'];

			$jumlah = $form_state['values']['jumlah'];
			$jumlahp = $form_state['values']['jumlahp'];
			$jumlahsesudah = $form_state['values']['jumlahsesudah'];
			
			
			for ($x = 1; $x <= $maxdetil; $x++) 
			{
				
				//Hitung detilnya dulu
				$uraian = $form_state['values']['uraian_' . $x];
				//drupal_set_message($uraian . ' - ' . $form_state['values']['iddetil_' . $x] . ' / ' . $form_state['values']['weight_' . $x] );
				if ($uraian != '') {
					
					$iddetil = $form_state['values']['iddetil_' . $x];
					$e_pengelompokan = $form_state['values']['e_pengelompokan_' . $x];
					$pengelompokan = $form_state['values']['pengelompokan_' . $x];
					$weight = $form_state['values']['weight_' . $x];

					if ($e_pengelompokan) {
						$unitjumlah = '1';
						$unitsatuan = '';
						$volumjumlah = '1';
						$volumsatuan = ''; 
						$harga = $form_state['values']['e_harga_' . $x];
						
					} else {
						$unitjumlah = $form_state['values']['unitjumlah_' . $x];
						$unitsatuan = $form_state['values']['unitsatuan_' . $x];
						$volumjumlah = $form_state['values']['volumjumlah_' . $x];
						$volumsatuan = $form_state['values']['volumsatuan_' . $x]; 
						$harga = $form_state['values']['harga_' . $x];
						
					}
					
					$total = $unitjumlah * $volumjumlah * $harga;
					$totalrekening += $total;
					
					//drupal_set_message($uraian . ' - ' . $weight);
					
					//Simpan detilnya
					if ($iddetil=='new') {
						//drupal_set_message('new ' . $kodero);
						$sql = 'insert into {anggperukdetilperubahan} (kodeuk, kodero, tahun, nourut, uraianp, unitjumlahp, unitsatuanp, volumjumlahp, volumsatuanp, hargap, totalp, pengelompokan, periode) 
								values(\'%s\', \'%s\', \'%s\', \'%s\', \'%s\', \'%s\', \'%s\', \'%s\', \'%s\', \'%s\', \'%s\', \'%s\', \'%s\')';        
						$res = db_query(db_rewrite_sql($sql), array($kodeuk, $kodero, $tahun, $weight, $uraian, $unitjumlah, $unitsatuan, $volumjumlah, $volumsatuan, $harga, $total, $pengelompokan, $periodeaktif));	
					} else {
						
						if ($pengelompokan) {
							$sql = 'update {anggperukdetilperubahan} set nourut=\'%s\', uraianp=\'%s\', unitjumlahp=\'%s\', unitsatuanp=\'%s\', volumjumlahp=\'%s\', volumsatuanp=\'%s\', 
								  pengelompokan=\'%s\' where iddetil=\'%s\' ';
							$res = db_query(db_rewrite_sql($sql), array($weight, $uraian, $unitjumlah, $unitsatuan, $volumjumlah, $volumsatuan, $pengelompokan, $iddetil));

						} else {
							
							$sql = 'update {anggperukdetilperubahan} set nourut=\'%s\', uraianp=\'%s\', unitjumlahp=\'%s\', unitsatuanp=\'%s\', volumjumlahp=\'%s\', volumsatuanp=\'%s\', 
								   hargap=\'%s\', totalp=\'%s\', pengelompokan=\'%s\' where iddetil=\'%s\' ';
							$res = db_query(db_rewrite_sql($sql), array($weight, $uraian, $unitjumlah, $unitsatuan, $volumjumlah, $volumsatuan, $harga, $total, $pengelompokan, $iddetil));
						}
					}
					
				} else {
					$iddetil = $form_state['values']['iddetil_' . $x];
					if ($iddetil!=='new') {
						
						$iddetil = $form_state['values']['iddetil_' . $x];
						$periode = $form_state['values']['periode_' . $x];
						
						if ($periode==$periodeaktif) {
							$sql = 'delete from {anggperukdetilperubahan} WHERE iddetil=\'%s\'';
							$res = db_query(db_rewrite_sql($sql), array($iddetil));
							
						} else {

							$unitjumlah = 0;
							$unitsatuan = '';
							$volumjumlah = 0;
							$volumsatuan = ''; 
							$harga = 0;
							$total =0;
							
							$sql = 'update {anggperukdetilperubahan} set nourut=\'%s\', uraianp=\'%s\', unitjumlahp=\'%s\', unitsatuanp=\'%s\', volumjumlahp=\'%s\', volumsatuanp=\'%s\', 
								   hargap=\'%s\', totalp=\'%s\', pengelompokan=\'%s\' where iddetil=\'%s\' ';
							$res = db_query(db_rewrite_sql($sql), array($weight, $uraian, $unitjumlah, $unitsatuan, $volumjumlah, $volumsatuan, $harga, $total, $pengelompokan, $iddetil));					}
						
					}
					
				}

			}
			
			if ($totalrekening<0) $totalrekening=0;
			
			if ($e_kodero=='') {
				$sql = 'insert into {anggperukperubahan} (kodeuk,tahun,kodero,uraian,jumlah,jumlahp,jumlahsesudah, ketrekening, periode) 
					   values (\'%s\', \'%s\', \'%s\', \'%s\', \'%s\', \'%s\', \'%s\', \'%s\', \'%s\')';        
				$res = db_query(db_rewrite_sql($sql), array($kodeuk, $tahun, $kodero,$uraianrek, 0, $totalrekening, $jumlahsesudah, $ketrekening, $periodeaktif));
				
				
			} else {
				$sql = 'update {anggperukperubahan} set uraian=\'%s\', kodero=\'%s\', jumlahp=\'%s\', jumlahsesudah=\'%s\', ketrekening=\'%s\' where kodeuk=\'%s\' and kodero=\'%s\' and tahun=\'%s\'';
				$res = db_query(db_rewrite_sql($sql), array($uraianrek, $kodero, $totalrekening, $jumlahsesudah, $ketrekening, $kodeuk, $e_kodero, $tahun));
			}
			
			if($form_state['clicked_button']['#value'] == $form_state['values']['submitnew']) {
				$nextkode = $form_state['values']['nextkode'];
				$form_state['redirect'] = 'apbdpendapatanperubahan/'  . $kodeuk ;

			} else if ($form_state['clicked_button']['#value'] == $form_state['values']['submitnewdetil']) {
				$form_state['redirect'] = 'apbdpendapatanperubahan/'  . $kodeuk . '/' . $kodero  ;
				
			} else {
				
				if ($res)
					drupal_set_message('Penyimpanan data berhasil dilakukan');
				else
					drupal_set_message('Penyimpanan data tidak berhasil dilakukan');
				//drupal_goto('apbd/pendapatanperubahan/');      
			}
		}
	}
	else{
			if ($form_state['clicked_button']['#value'] == $form_state['values']['submit']) 	//APV
			$persetujuan = 1;
			
		else if ($form_state['clicked_button']['#value'] == $form_state['values']['submittolak']) 	//REJECT
			$persetujuan = 0;
		
		else
			$persetujuan = -1;
		
		if ($persetujuan >= 0) {
			if ($ada == false) {
				$sql = 'insert into {anggperukrevisiverifikasi} (kodero,kodeuk, username, jawaban, persetujuan) values(\'%s\',\'%s\',\'%s\',\'%s\',\'%s\')';
				$res = db_query(db_rewrite_sql($sql), array($kodero,$kodeuk, $username, $jawaban, $persetujuan));
			
			} else {
				$sql = 'update {anggperukrevisiverifikasi} set kodeuk=\'%s\',jawaban=\'%s\', persetujuan=\'%s\' where kodero=\'%s\' and username=\'%s\'';
				$res = db_query(db_rewrite_sql($sql), array($kodeuk,$jawaban, $persetujuan, $kodero, $username));
				
			}
			
		} else {
			$sql = 'delete from {kegiatanverifikasi} where kodekeg=\'%s\' and username=\'%s\'';
			$res = db_query(db_rewrite_sql($sql), array($kodekeg, $username));
		}	
		if ($res) 
			drupal_goto('/apbd/pendapatanperubahan');
		else
			drupal_set_message('Penyimpanan gagal');
	}
    
	
	
}
 
/**
 * Implementation of hook_theme().
 */
function apbdpendapatanperubahan_theme() {
    return array(
        'apbdpendapatanperubahan_form' => array(
            'arguments' => array(
                'form' => NULL
            ),
        ),
    );
}
 
/**
 * Theme for form_element_form. Used to create the tabledrag element and then
 * render the rest of the form.
 */
function theme_apbdpendapatanperubahan_form($form) {
    $table_rows = array();
 
    if (is_array($form['tabledragrows'])) {
        //loop through each "row" in the table array
        foreach ($form['tabledragrows'] as $id => $row) {
            //we are only interested in numeric keys
            if (intval($id)) {
                $this_row = array();
				
				//$this_row[] = drupal_render($form['tabledragrows'][$id]['iddetil_' . $id]);
				$this_row[] = drupal_render($form['tabledragrows'][$id]['space_' . $id]);
				$this_row[] = drupal_render($form['tabledragrows'][$id]['pengelompokan_' . $id]);
                $this_row[] = drupal_render($form['tabledragrows'][$id]['uraian_' . $id]);
                $this_row[] = drupal_render($form['tabledragrows'][$id]['unitjumlah_' . $id]);
				$this_row[] = drupal_render($form['tabledragrows'][$id]['unitsatuan_' . $id]);
                $this_row[] = drupal_render($form['tabledragrows'][$id]['volumjumlah_' . $id]);
				$this_row[] = drupal_render($form['tabledragrows'][$id]['volumsatuan_' . $id]);
				$this_row[] = drupal_render($form['tabledragrows'][$id]['harga_' . $id]);
				
				$this_row[] = drupal_render($form['tabledragrows'][$id]['subdetil_' . $id]);
				
                //Add the weight field to the row
                $this_row[] = drupal_render($form['tabledragrows'][$id]['weight_' . $id]);
 
                //Add the row to the array of rows
                $table_rows[] = array('data' => $this_row, 'class' => 'draggable');
            }
        }
    }
 
    //Make sure the header count matches the column count
    //$header = array(
     //   "Person",
    //    "Email",
    //    "Weight"
    //);
	$header = array (
				array('data' => '',  'width'=> '0px'),
				array('data' => 'Grp',  'width'=> '5px'),
				 array('data' => 'Uraian',  'width'=> '30px'),
				 array('data' => 'Unit',  'width' => '10px'),
				 array('data' => '',  'width' => '30px'),
				 array('data' => 'Volume',  'width' => '10px'),
				 array('data' => '',  'width' => '30px'),
				 array('data' => 'Harga',  'width' => '20px'),
				 array('data' => '',  'width' => '5px'),
				 array('data' => 'Weight'),
				); 
	if(!isVerifikator()){
		$form['tabledragrows'] = array(
        '#value' => theme('table', $header, $table_rows, array('id' => 'id'))
    );
	}
    
 
    $output = drupal_render($form);
 
    // Call add_tabledrag to add and setup the JavaScript
    // The key thing here is the first param - the table ID
    // and the 4th param, the class of the form item which holds the weight
    drupal_add_tabledrag('id', 'order', 'sibling', 'weight');
 
    return $output;
}