<?php
 
/**
 * For more informaiton about the different API controls available see:
 * http://api.drupal.org/api/drupal/developer--topics--forms_api_reference.html/6
 */
 
function apbdpendapatan_menu() {
    $items['apbdpendapatan'] = array(
        'title' => 'Rekening Pendapatan',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('apbdpendapatan_form'),
        'access callback' => TRUE,
    );
    return $items;
}
 
/**
 * This is form containing every form element type available.
 */
function apbdpendapatan_form() {
	
	drupal_add_css('files/css/kegiatancam.css');
	drupal_add_js('files/js/kegiatanpad.js');
    $form['formdata'] = array (
        '#type' => 'fieldset',
        '#title'=> 'Rekening Pendapatan',
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,        
    );
	
	$kodeuk = arg(1);
	$kodero = arg(2);
	//drupal_set_message($kodeuk);
	
	if (!isSuperuser())
		$kodeuk = apbd_getuseruk();
		
	//drupal_set_message($kodeuk);
	

	$title = 'Rekening Pendapatan';

	
	$allowedit = (batastgl() || (isSuperuser()));	

	if ($allowedit==false) {
		//dispensasippas
		//$sqluk = sprintf(' and k.kodeuk=\'%s\' ', apbd_getuseruk());	
        $sql = sprintf('select dispensasippas from {unitkerja} where kodeuk=\'%s\'', apbd_getuseruk());
		$res = db_query($sql);
		if ($res) {
			$data = db_fetch_object($res);
			if ($data) {  		
				$allowedit = $data->dispensasippas;
			}
		}
	}
	
	//$title =l($title, 'apbd/pendapatan/' . $kodeuk, array('html'=>true));
	drupal_set_title($title);
	drupal_set_html_head('<style>label{font-weight: bold; display: block; width: 200px; float: left;}</style>');
    $disabled = FALSE;

	$jumlah = 0;
	$jumlahsebelum = 0;
	$jumlahsesudah = 0;
	//$uraian = 'Isikan rekening dengan mengklik tombol Pilih disamping';

	//FILTER TAHUN-----
	$tahun = variable_get('apbdtahun', 0);
	
    if (isset($kodero))
    {
        if (!user_access('kegiatanskpd edit'))
            drupal_access_denied();
			
        $sql = 'select tahun,kodero,uraian,jumlah,jumlahsebelum,jumlahsesudah,ketrekening from {anggperuk} 
			   where tahun=\'%s\' and kodeuk=\'%s\' and kodero=\'%s\'';
        $res = db_query(db_rewrite_sql($sql), array ($tahun, $kodeuk, $kodero));
        if ($res) {
            $data = db_fetch_object($res);
			if ($data) {
                
				$kodero = $data->kodero;
				$uraian = $data->uraian;
				$jumlah = $data->jumlah;
				$jumlahsebelum = $data->jumlahsebelum;
				$jumlahsesudah = $data->jumlahsesudah;
				$ketrekening = $data->ketrekening;
                $disabled =TRUE;
			} else {
				$kodero = '';
			}
        } else {
			$kodero = '';
		}
    } else {
		if (!user_access('kegiatanskpd tambah'))
			drupal_access_denied();
		$form['formdata']['#title'] = 'Tambah Rekening Pendapatan';
		$kodero = '';
	}

    
	$form['formdata']['tahun']= array( 
		'#type'         => 'hidden', 
		'#title'        => 'tahun',  
		'#default_value'=> $tahun, 
	); 	
	$form['formdata']['nk']= array(
		'#type'         => 'hidden', 
		'#title'        => 'kodero', 
		'#default_value'=> $kodero, 
	); 
	$form['formdata']['e_kodero']= array(
		'#type'         => 'hidden', 
		'#title'        => 'kodero', 
		'#default_value'=> $kodero, 
	); 

	$pquery = "select kodeuk, namasingkat from {unitkerja} where aktif=1 order by namauk" ;
	$pres = db_query($pquery);
	$skpd = array();
	$dinas[''] = '--- pilih dinas teknis---';
	while ($data = db_fetch_object($pres)) {
		$skpd[$data->kodeuk] = $data->namasingkat;
	}
	$skpdtype = 'hidden';
	if (isSuperuser() || isAdministrator())
		$skpdtype='select';

	$form['formdata']['kodeuk']= array(
		'#type'         => $skpdtype, 
		'#title'        => 'SKPD',
		'#options'		=> $skpd,
		//'#description'  => 'kodeuk', 
		//'#maxlength'    => 60, 
		//'#size'         => 20, 
		//'#required'     => !$disabled, 
		//'#disabled'     => $disabled, 
		'#default_value'=> $kodeuk, 
	); 
		
	$form['formdata']['kegiatan']= array(
		'#type'         => 'textfield', 
		'#title'        => 'Rekening', 
		//'#description'  => 'uraian', 
		'#maxlength'    => 255, 
		'#size'         => 70, 
		//'#required'     => !$disabled, 
		//'#disabled'     => $disabled, 
		//'#autocomplete_path' => 'apbd/kegiatanrkpd/utils_auto/uraianpendapatan',
		'#default_value'=> $uraian, 
	); 
	$form['formdata']['keterangan'] = array (
		'#type' => 'markup',
		'#value' => "<span><font size='1'>Isi rekening dengan memilih menggunakan tombol Pilih</font></span>",
	);

	$form['formdata']['ketrekening']= array(
		'#type'         => 'textfield', 
		'#title'        => 'Dasar Hukum', 
		//'#description'  => 'Rekening belanja', 
		'#maxlength'    => 255, 
		'#size'         => 70, 
		//'#required'     => !$disabled, 
		//'#disabled'     => $disabled, 
		'#default_value'=> $ketrekening, 
	); 
	
	$form['formdata']['jumlah']= array(
		'#type'         => 'textfield', 
		'#title'        => 'Jumlah',
		'#attributes'	=> array('style' => 'text-align: right'),
		'#disabled'     => true, 
		'#description'  => 'Jumlah anggaran pendapatan, akan terisi saat detil rekening diisikan', 
		//'#maxlength'    => 60, 
		'#size'         => 30, 
		//'#required'     => !$disabled, 
		//'#disabled'     => $disabled, 
		'#default_value'=> $jumlah, 
	); 
	$form['formdata']['jumlahsebelum']= array(
		'#type'         => 'hidden', 
		'#title'        => 'Tahun Lalu',
		'#attributes'	=> array('style' => 'text-align: right'),
		'#description'  => 'Jumlah anggaran pendapatan tahun lalu, seandainya ada', 
		//'#maxlength'    => 60, 
		'#size'         => 30, 
		//'#required'     => !$disabled, 
		//'#disabled'     => $disabled, 
		'#default_value'=> $jumlahsebelum, 
	); 
	$form['formdata']['jumlahsesudah']= array(
		'#type'         => 'textfield', 
		'#title'        => 'Tahun Depan',
		'#attributes'	=> array('style' => 'text-align: right'),
		'#description'  => 'Jumlah perkiraan anggaran pendapatan tahun depan, seandainya ada', 
		//'#maxlength'    => 60, 
		'#size'         => 30, 
		//'#required'     => !$disabled, 
		//'#disabled'     => $disabled, 
		'#default_value'=> $jumlahsesudah, 
	);
	
	//DETIL
	$where = sprintf(" where kodeuk='%s' and kodero='%s' and tahun='%s'", db_escape_string($kodeuk), db_escape_string($kodero), db_escape_string($tahun));
    $sql = 'select iddetil,kodeuk,kodero,uraian,unitjumlah,unitsatuan,volumjumlah,
			volumsatuan,harga,total,pengelompokan 
			from {anggperukdetil}' . $where  . ' order by nourut asc,iddetil';
    $sql = sprintf($sql, addslashes($nama));
	
	//drupal_set_message($sql);
	$resdetil = db_query($sql);
	$weight = 0;
	$rows= array();
	if ($resdetil) {
		//drupal_set_message('res ok');
		while ($data = db_fetch_object($resdetil)) {
			$weight += 1;
			//drupal_set_message($data->uraian . ' - ' . $weight);
			
			if ($data->pengelompokan) {
				$subdetil = l('Detil', 'apbdpendapatandetil/' . $kodeuk . '/' . $kodero . '/' . $data->iddetil , array('html' =>TRUE));			
				$rows[] = array (
								'id' => $weight,
								'iddetil' => $data->iddetil,
								'space' => '',
								'pengelompokan' => $data->pengelompokan,
								'e_pengelompokan' => $data->pengelompokan,
								'uraian' => $data->uraian,
								'unitjumlah' => '1',
								'unitsatuan' => '',
								'volumjumlah' => '1',
								'volumsatuan' => '',
								'harga' => $data->total,
								'e_harga' => $data->total,
								'subdetil' => $subdetil,
								'weight' => $weight,
							);

			} else {
				$subdetil = '';			
				$rows[] = array (
								'id' => $weight,
								'iddetil' => $data->iddetil,
								'space' => '',
								'pengelompokan' => $data->pengelompokan,
								'e_pengelompokan' => $data->pengelompokan,								
								'uraian' => $data->uraian,
								'unitjumlah' => $data->unitjumlah,
								'unitsatuan' => $data->unitsatuan,
								'volumjumlah' => $data->volumjumlah,
								'volumsatuan' => $data->volumsatuan,
								'harga' => $data->harga,
								'e_harga' => $data->harga,
								'subdetil' => $subdetil,
								'weight' => $weight,
							);
			}
		}
	}
	
	for ($x = 1; $x <= 5; $x++) {
		$weight += 1;

		$rows[] = array (
						'id' => $weight,
						'iddetil' => 'new',
						'space' => '',
						'pengelompokan' => '',
						'e_pengelompokan' => '',
						'uraian' => '',
						'unitjumlah' => '1',
						'unitsatuan' => '',
						'volumjumlah' => '1',
						'volumsatuan' => '',
						'harga' => '',
						'e_harga' => '',
						'subdetil' => '',
						'weight' => $weight,
					);
	}
	
    // Tabledrag element
    foreach ($rows as $row) {
        $form['tabledragrows'][$row['id']]['iddetil_' . $row['id']] = array(
            '#type' => 'hidden',
            '#default_value' => $row['iddetil'],
            '#size' => 10,
        );

        $form['tabledragrows'][$row['id']]['space_' . $row['id']] = array(
            '#type' => 'markup',
            '#default_value' => '',
            '#size' => 10,
        );

        $form['tabledragrows'][$row['id']]['pengelompokan_' . $row['id']] = array(
            '#type' => 'checkbox',
            '#default_value' => $row['pengelompokan'],
            '#size' => 10,
        );

        $form['tabledragrows'][$row['id']]['e_pengelompokan_' . $row['id']] = array(
            '#type' => 'hidden',
            '#default_value' => $row['e_pengelompokan'],
            '#size' => 10,
        );


		$form['tabledragrows'][$row['id']]['uraian_' . $row['id']] = array(
			'#type' => 'textfield',
			'#default_value' => $row['uraian'],
			'#size' => 45,
		);

        $form['tabledragrows'][$row['id']]['unitjumlah_' . $row['id']] = array(
            '#type' => 'textfield',
            '#default_value' => $row['unitjumlah'],
			'#attributes'	=> array('style' => 'text-align: right'),
            '#size' => 5,
        );
        $form['tabledragrows'][$row['id']]['unitsatuan_' . $row['id']] = array(
            '#type' => 'textfield',
            '#default_value' => $row['unitsatuan'],
            '#size' => 10,
        );

        $form['tabledragrows'][$row['id']]['volumjumlah_' . $row['id']] = array(
            '#type' => 'textfield',
            '#default_value' => $row['volumjumlah'],
			'#attributes'	=> array('style' => 'text-align: right'),
            '#size' => 5,
        );
        $form['tabledragrows'][$row['id']]['volumsatuan_' . $row['id']] = array(
            '#type' => 'textfield',
            '#default_value' => $row['volumsatuan'],
            '#size' => 10,
        );

        $form['tabledragrows'][$row['id']]['harga_' . $row['id']] = array(
            '#type' => 'textfield',
            '#default_value' => $row['harga'],
			'#attributes'	=> array('style' => 'text-align: right'),
            '#size' => 10,
        );

        $form['tabledragrows'][$row['id']]['e_harga_' . $row['id']] = array(
            '#type' => 'hidden',
            '#default_value' => $row['e_harga'],
            '#size' => 10,
        );
		
		//'#value' => "<span>$data->program (Kode: $data->kodepro)</span>",
        $form['tabledragrows'][$row['id']]['subdetil_' . $row['id']] = array(
            '#type' => 'markup',
            //'#default_value' => $row['subdetil'],
			//'#value' => "<span>Hai</span>",
			'#value' => $row['subdetil'],
            '#size' => 5,
        );
		
        // the weight form element.
        $form['tabledragrows'][$row['id']]['weight_' . $row['id']] = array(
            '#type' => 'weight',
            '#delta' => 50,
            '#default_value' => $row['weight'],
            '#attributes' => array('class' => 'weight'),
        );
    }
 
	$form['maxdetil']= array(
		'#type'         => 'hidden', 
		'#title'        => 'kodero', 
		'#default_value'=> $weight, 
	); 
 
	if ($kodero != '') {
		//PREV
		$sql = 'select kodero from {anggperuk} where kodeuk=\'%s\' and kodero<\'%s\' order by kodero desc limit 1';
		$res = db_query(db_rewrite_sql($sql), array ($kodeuk, $kodero));
		if ($res) {
			$data = db_fetch_object($res);
			if ($data) {
				$prevkode=$data->kodero;

				$form['prevkode']= array(
					'#type'         => 'hidden', 
					'#default_value'=> $prevkode, 
					//'#weight' => 1,
				);				
				
				
				$form['formdata']['submitprev'] = array (
					'#type' => 'submit',
					'#value' => '<<',
					//'#weight' => 2,
				); 

				$form['submitprev'] = array (
					'#type' => 'submit',
					'#value' => '<<',
					//'#weight' => 2,
				); 
				
			}
		}	
		
		//NEXT
		$sql = 'select kodero from {anggperuk} where kodeuk=\'%s\' and kodero>\'%s\' order by kodero limit 1';
		$res = db_query(db_rewrite_sql($sql), array ($kodeuk, $kodero));
		if ($res) {
			$data = db_fetch_object($res);
			if ($data) {
				$nextkode=$data->kodero;

				$form['nextkode']= array(
					'#type'         => 'hidden', 
					'#default_value'=> $nextkode, 
					//'#weight' => 3,
				);				

				$form['formdata']['submitnext'] = array (
					'#type' => 'submit',
					'#value' => '>>',
					//'#weight' => 4,
				);

				$form['submitnext'] = array (
					'#type' => 'submit',
					'#value' => '>>',
					//'#weight' => 4,
				);
				
			}
		}		
	}

 	$form['formdata']['submitnew'] = array (
		'#type' => 'submit',
		'#value' => 'Rek. Baru',
		//'#weight' => 5,
	);
 	$form['submitnew'] = array (
		'#type' => 'submit',
		'#value' => 'Rek. Baru',
		//'#weight' => 5,
	);

 	$form['formdata']['submitnewdetil'] = array (
		'#type' => 'submit',
		'#value' => 'Tambah Detil',
		//'#weight' => 6,
	);
 	$form['submitnewdetil'] = array (
		'#type' => 'submit',
		'#value' => 'Tambah Detil',
		//'#weight' => 6,
	);
	
    $form['formdata']['submit'] = array(
        '#type' => 'submit',
		'#suffix' => "&nbsp;<a href='/apbd/pendapatan/" . "' class='btn_blue' style='color: white'>Tutup</a>",
        '#value' => 'Simpan',
		//'#weight' => 7,
    );
    $form['submit'] = array(
        '#type' => 'submit',
		'#suffix' => "&nbsp;<a href='/apbd/pendapatan/" . "' class='btn_blue' style='color: white'>Tutup</a>",
        '#value' => 'Simpan',
		//'#weight' => 7,
    );
 
    return $form;
}

/**
 * Implements hook_validate() for the apbdpendapatan_form() form.
 */
function apbdpendapatan_form_validate($form, &$form_state) {
	$uraianrek = $form_state['values']['kegiatan'];
	$kodero = $form_state['values']['nk'];

	$kodeuk = $form_state['values']['kodeuk'];
	$e_kodero = $form_state['values']['e_kodero'];
	
	$maxdetil = $form_state['values']['maxdetil'];

	if ($kodero=='') 
		form_set_error('', 'Rekening belum diisi');
	
	
	if ($e_kodero != $kodero) {		//Rekening baru
		$sql = 'select kodero from {anggperuk} where kodeuk=\'%s\' and kodero=\'%s\'';
		$res = db_query(db_rewrite_sql($sql), array ($kodeuk, $kodero));
		if ($res) {
			$data = db_fetch_object($res);
			if ($data) {		
				form_set_error('', 'Rekening sudah digunakan');
			}
		}
	} 
	
	//CEK PLAFON
	$totalrekening = 0;
	for ($x = 1; $x <= $maxdetil; $x++) 
	{
		//Hitung detilnya dulu
		$uraian = $form_state['values']['uraian_' . $x];
		$e_pengelompokan = $form_state['values']['e_pengelompokan_' . $x];
		if ($uraian != '') {
			if ($e_pengelompokan) {
				$total = $form_state['values']['e_harga_' . $x];
				
			} else {
				$unitjumlah = $form_state['values']['unitjumlah_' . $x];
				$volumjumlah = $form_state['values']['volumjumlah_' . $x];
				$harga = $form_state['values']['harga_' . $x];

				$total = $unitjumlah * $volumjumlah * $harga;
			}
			$totalrekening += $total;
			
		} 

	}

	//CEK PER 1000
	$seribu = 1000;
	//if ($totalrekening==0)
	//	form_set_error('', 'Isian rekening belum dimasukkan dengan benar, anda harus mengisi detil rekening sehingga jumlah anggaran rekening ada nominal rupiahnya');
	if (($totalrekening % $seribu)>0) form_set_error('', 'Jumlah isian detil rekening ' . apbd_fn($totalrekening) . ', tidak bulat per seribu');

} 
/**
 * Implements hook_submit() for the apbdpendapatan_form() form.
 */
function apbdpendapatan_form_submit($form, &$form_state) {
    
	$kodeuk = $form_state['values']['kodeuk'];
	$tahun = $form_state['values']['tahun'];
	
    if($form_state['clicked_button']['#value'] == $form_state['values']['submitnext']) {
		$nextkode = $form_state['values']['nextkode'];
        $form_state['redirect'] = 'apbdpendapatan/' .  $kodeuk . '/' . $nextkode ;
		//drupal_set_message('Next');

	} else if($form_state['clicked_button']['#value'] == $form_state['values']['submitprev']) {
		$prevkode = $form_state['values']['prevkode'];
        $form_state['redirect'] = 'apbdpendapatan/' . $kodeuk . '/' . $prevkode ;
		//drupal_set_message('Next');

	} else {
		
		$e_kodero = $form_state['values']['e_kodero'];			

		
		$uraianrek = $form_state['values']['kegiatan'];
		$kodero = $form_state['values']['nk'];
		$maxdetil = $form_state['values']['maxdetil'];

		$jumlah = $form_state['values']['jumlah'];
		$jumlahsebelum = $form_state['values']['jumlahsebelum'];
		$jumlahsesudah = $form_state['values']['jumlahsesudah'];
		
		/*
		if (($kodero=='') and ($uraianrek !='')) {		//Rekening diisi dari mengetik
			$sql = 'select kodero from {rincianobyek} where uraian=\'%s\'';
			$res = db_query(db_rewrite_sql($sql), array ($uraian));
			if ($res) {
				$data = db_fetch_object($res);
				if ($data) {
					
					$kodero = $data->kodero;
				} else {
					$kodero = '';
				}
			} else {
				$kodero = '';
			}
		}
		*/
		
		for ($x = 1; $x <= $maxdetil; $x++) 
		{
			
			//Hitung detilnya dulu
			$uraian = $form_state['values']['uraian_' . $x];
			//drupal_set_message($uraian . ' - ' . $form_state['values']['iddetil_' . $x] . ' / ' . $form_state['values']['weight_' . $x] );
			if ($uraian != '') {
				
				$iddetil = $form_state['values']['iddetil_' . $x];
				$e_pengelompokan = $form_state['values']['e_pengelompokan_' . $x];
				$pengelompokan = $form_state['values']['pengelompokan_' . $x];
				$weight = $form_state['values']['weight_' . $x];

				if ($e_pengelompokan) {
					$unitjumlah = '1';
					$unitsatuan = '';
					$volumjumlah = '1';
					$volumsatuan = ''; 
					$harga = $form_state['values']['e_harga_' . $x];
					
				} else {
					$unitjumlah = $form_state['values']['unitjumlah_' . $x];
					$unitsatuan = $form_state['values']['unitsatuan_' . $x];
					$volumjumlah = $form_state['values']['volumjumlah_' . $x];
					$volumsatuan = $form_state['values']['volumsatuan_' . $x]; 
					$harga = $form_state['values']['harga_' . $x];
					
				}
				
				$total = $unitjumlah * $volumjumlah * $harga;
				$totalrekening += $total;
				
				//drupal_set_message($uraian . ' - ' . $weight);
				
				//Simpan detilnya
				if ($iddetil=='new') {
					//drupal_set_message('new ' . $kodero);
					$sql = 'insert into {anggperukdetil} (kodeuk, kodero, tahun, nourut, uraian, unitjumlah, unitsatuan, volumjumlah, volumsatuan, harga, total, pengelompokan) 
							values(\'%s\', \'%s\', \'%s\', \'%s\', \'%s\', \'%s\', \'%s\', \'%s\', \'%s\', \'%s\', \'%s\', \'%s\')';        
					$res = db_query(db_rewrite_sql($sql), array($kodeuk, $kodero, $tahun, $weight, $uraian, $unitjumlah, $unitsatuan, $volumjumlah, $volumsatuan, $harga, $total, $pengelompokan));	
				} else {
					
					if ($pengelompokan) {
						$sql = 'update {anggperukdetil} set nourut=\'%s\', uraian=\'%s\', unitjumlah=\'%s\', unitsatuan=\'%s\', volumjumlah=\'%s\', volumsatuan=\'%s\', 
							  pengelompokan=\'%s\' where iddetil=\'%s\' ';
						$res = db_query(db_rewrite_sql($sql), array($weight, $uraian, $unitjumlah, $unitsatuan, $volumjumlah, $volumsatuan, $pengelompokan, $iddetil));

					} else {
						
						$sql = 'update {anggperukdetil} set nourut=\'%s\', uraian=\'%s\', unitjumlah=\'%s\', unitsatuan=\'%s\', volumjumlah=\'%s\', volumsatuan=\'%s\', 
							   harga=\'%s\', total=\'%s\', pengelompokan=\'%s\' where iddetil=\'%s\' ';
						$res = db_query(db_rewrite_sql($sql), array($weight, $uraian, $unitjumlah, $unitsatuan, $volumjumlah, $volumsatuan, $harga, $total, $pengelompokan, $iddetil));
					}
				}
				
			} else {
				$iddetil = $form_state['values']['iddetil_' . $x];
				if ($iddetil!=='new') {

					$iddetil = $form_state['values']['iddetil_' . $x];
				
					$sql = 'delete from {anggperukdetil} WHERE iddetil=\'%s\'';
					$res = db_query(db_rewrite_sql($sql), array($iddetil));
					
				}
				
			}

		}
		
		if ($totalrekening<0) $totalrekening=0;
		
		if ($e_kodero=='') {
			$sql = 'insert into {anggperuk} (kodeuk,tahun,kodero,uraian,jumlah,jumlahsebelum,jumlahsesudah) 
				   values (\'%s\', \'%s\', \'%s\', \'%s\', \'%s\', \'%s\', \'%s\')';        
			$res = db_query(db_rewrite_sql($sql), array($kodeuk, $tahun, $kodero,$uraianrek, $totalrekening, $jumlahsebelum, $jumlahsesudah));
			
			
		} else {
			$sql = 'update {anggperuk} set uraian=\'%s\', kodero=\'%s\', jumlah=\'%s\', jumlahsebelum=\'%s\', jumlahsesudah=\'%s\' where kodeuk=\'%s\' and kodero=\'%s\' and tahun=\'%s\'';
			$res = db_query(db_rewrite_sql($sql), array($uraianrek, $kodero, $totalrekening, $jumlahsebelum, $jumlahsesudah, $kodeuk, $e_kodero, $tahun));
		}
		
		if($form_state['clicked_button']['#value'] == $form_state['values']['submitnew']) {
			$nextkode = $form_state['values']['nextkode'];
			$form_state['redirect'] = 'apbdpendapatan/'  . $kodeuk ;

		} else if ($form_state['clicked_button']['#value'] == $form_state['values']['submitnewdetil']) {
			$form_state['redirect'] = 'apbdpendapatan/'  . $kodeuk . '/' . $kodero  ;
			
		} else {
			
			if ($res)
				drupal_set_message('Penyimpanan data berhasil dilakukan');
			else
				drupal_set_message('Penyimpanan data tidak berhasil dilakukan');
			//drupal_goto('apbd/pendapatan/' . $kodeuk);      
		}
	}
	
	
}
 
/**
 * Implementation of hook_theme().
 */
function apbdpendapatan_theme() {
    return array(
        'apbdpendapatan_form' => array(
            'arguments' => array(
                'form' => NULL
            ),
        ),
    );
}
 
/**
 * Theme for form_element_form. Used to create the tabledrag element and then
 * render the rest of the form.
 */
function theme_apbdpendapatan_form($form) {
    $table_rows = array();
 
    if (is_array($form['tabledragrows'])) {
        //loop through each "row" in the table array
        foreach ($form['tabledragrows'] as $id => $row) {
            //we are only interested in numeric keys
            if (intval($id)) {
                $this_row = array();
				
				//$this_row[] = drupal_render($form['tabledragrows'][$id]['iddetil_' . $id]);
				$this_row[] = drupal_render($form['tabledragrows'][$id]['space_' . $id]);
				$this_row[] = drupal_render($form['tabledragrows'][$id]['pengelompokan_' . $id]);
                $this_row[] = drupal_render($form['tabledragrows'][$id]['uraian_' . $id]);
                $this_row[] = drupal_render($form['tabledragrows'][$id]['unitjumlah_' . $id]);
				$this_row[] = drupal_render($form['tabledragrows'][$id]['unitsatuan_' . $id]);
                $this_row[] = drupal_render($form['tabledragrows'][$id]['volumjumlah_' . $id]);
				$this_row[] = drupal_render($form['tabledragrows'][$id]['volumsatuan_' . $id]);
				$this_row[] = drupal_render($form['tabledragrows'][$id]['harga_' . $id]);
				
				$this_row[] = drupal_render($form['tabledragrows'][$id]['subdetil_' . $id]);
				
                //Add the weight field to the row
                $this_row[] = drupal_render($form['tabledragrows'][$id]['weight_' . $id]);
 
                //Add the row to the array of rows
                $table_rows[] = array('data' => $this_row, 'class' => 'draggable');
            }
        }
    }
 
    //Make sure the header count matches the column count
    //$header = array(
     //   "Person",
    //    "Email",
    //    "Weight"
    //);
	$header = array (
				array('data' => '',  'width'=> '0px'),
				array('data' => 'Grp',  'width'=> '5px'),
				 array('data' => 'Uraian',  'width'=> '30px'),
				 array('data' => 'Unit',  'width' => '10px'),
				 array('data' => '',  'width' => '30px'),
				 array('data' => 'Volume',  'width' => '10px'),
				 array('data' => '',  'width' => '30px'),
				 array('data' => 'Harga',  'width' => '20px'),
				 array('data' => '',  'width' => '5px'),
				 array('data' => 'Weight'),
				); 
 
    $form['tabledragrows'] = array(
        '#value' => theme('table', $header, $table_rows, array('id' => 'id'))
    );
 
    $output = drupal_render($form);
 
    // Call add_tabledrag to add and setup the JavaScript
    // The key thing here is the first param - the table ID
    // and the 4th param, the class of the form item which holds the weight
    drupal_add_tabledrag('id', 'order', 'sibling', 'weight');
 
    return $output;
}